modLoader="javafml"
loaderVersion="[36,)" 
license="MIT"
issueTrackerURL="" 

[[mods]]
modId="bouncingball" 
version="1.0.0"
displayName="Bouncing Ball Mod" 
authors="YourName" 
description='Mod that adds a bouncing ball'

[[dependencies.bouncingball]]
modId="forge" 
mandatory=true 
versionRange="[36.1.0,)" 
ordering="NONE"
side="BOTH"
[[dependencies.bouncingball]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
